/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LktSideDrawer {
    'title': string;
  }
  interface LktSideDrawerAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface LktSpinner {
    'show': boolean;
  }
  interface LktSpinnerAttributes extends StencilHTMLAttributes {
    'show'?: boolean;
  }

  interface LktStockFinder {}
  interface LktStockFinderAttributes extends StencilHTMLAttributes {
    'onLktSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface LktStockPrice {
    'stockSymbol': string;
  }
  interface LktStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LktSideDrawer': Components.LktSideDrawer;
    'LktSpinner': Components.LktSpinner;
    'LktStockFinder': Components.LktStockFinder;
    'LktStockPrice': Components.LktStockPrice;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'lkt-side-drawer': Components.LktSideDrawerAttributes;
    'lkt-spinner': Components.LktSpinnerAttributes;
    'lkt-stock-finder': Components.LktStockFinderAttributes;
    'lkt-stock-price': Components.LktStockPriceAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLLktSideDrawerElement extends Components.LktSideDrawer, HTMLStencilElement {}
  var HTMLLktSideDrawerElement: {
    prototype: HTMLLktSideDrawerElement;
    new (): HTMLLktSideDrawerElement;
  };

  interface HTMLLktSpinnerElement extends Components.LktSpinner, HTMLStencilElement {}
  var HTMLLktSpinnerElement: {
    prototype: HTMLLktSpinnerElement;
    new (): HTMLLktSpinnerElement;
  };

  interface HTMLLktStockFinderElement extends Components.LktStockFinder, HTMLStencilElement {}
  var HTMLLktStockFinderElement: {
    prototype: HTMLLktStockFinderElement;
    new (): HTMLLktStockFinderElement;
  };

  interface HTMLLktStockPriceElement extends Components.LktStockPrice, HTMLStencilElement {}
  var HTMLLktStockPriceElement: {
    prototype: HTMLLktStockPriceElement;
    new (): HTMLLktStockPriceElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'lkt-side-drawer': HTMLLktSideDrawerElement
    'lkt-spinner': HTMLLktSpinnerElement
    'lkt-stock-finder': HTMLLktStockFinderElement
    'lkt-stock-price': HTMLLktStockPriceElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'lkt-side-drawer': HTMLLktSideDrawerElement;
    'lkt-spinner': HTMLLktSpinnerElement;
    'lkt-stock-finder': HTMLLktStockFinderElement;
    'lkt-stock-price': HTMLLktStockPriceElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
